spring:
  application:
    name: service-query-microservice
  
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  
  graphql:
    graphiql:
      enabled: true
    path: /graphql
